version: '3.8'

services:
  api:
    build: .
    ports:
      - "${API_PORT}:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=${REDIS_URL}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory ${REDIS_MAX_MEMORY:-512mb} --maxmemory-policy ${REDIS_MAX_MEMORY_POLICY:-allkeys-lru}
    volumes:
      - redis_data:/data

volumes:
  redis_data: